# Sources
source 'http://rubygems.org'
ruby '2.6.3'

gem 'bundler',  '~> 2'
gem 'puma'
gem 'mysql2' #,  '~> 0.4.10'
gem 'rails-i18n'
gem "kaminari"
gem 'prawn'
gem 'prawn-table'
gem 'okcomputer'
gem 'sass-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails', '~> 5.0.5'
gem 'execjs'
gem 'rollbar'
gem 'newrelic_rpm'
gem 'rbnacl-libsodium'
gem 'simple_form'
gem 'sass'
gem 'sassc-rails'
gem 'bcrypt'
gem 'bson'
gem 'nokogiri', '~> 1.13.5'
gem 'mongoid', '~> 7.0'
gem 'devise-i18n'
gem 'bootstrap', '~> 4.3.1'
gem 'jquery-rails'
gem 'rails', '~> 5.2.2'


